"""Login / logout blueprint for admin auth.

Endpoints:
    GET  /admin/login   -> render login form
    POST /admin/login   -> validate credentials, set session cookie
    GET  /admin/logout  -> clear session cookie, redirect to login

CSRF: handled by Flask-WTF's CSRFProtect (registered in `auth.init_app`).
The form template includes a hidden `csrf_token` field generated by the
`csrf_token()` Jinja global. Choice rationale: Flask-WTF gives us
defense-in-depth (signed-cookie session + per-form token) with no extra
moving parts vs. a hand-rolled double-submit cookie pattern.

Session key: Flask-Login uses Flask's signed-cookie session under its own
`_user_id` / `_id` keys, completely separate from the existing `unlocked`
key used by the $49 unlock flow. The two coexist in the same cookie without
interference.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

from flask import (
    Blueprint,
    Response,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import login_required, login_user, logout_user

from review_app.auth.models import User
from review_app.db import get_session

auth_bp = Blueprint("auth", __name__, url_prefix="/admin")


def _is_safe_redirect(target: str | None) -> bool:
    """Reject open redirects: only allow same-host relative URLs."""
    if not target:
        return False
    parsed = urlparse(target)
    # Reject anything with a scheme or netloc — only path-only URLs are safe.
    return not parsed.scheme and not parsed.netloc and target.startswith("/")


@auth_bp.route("/login", methods=["GET", "POST"])
def login() -> Response | str:
    """Render the login form (GET) or process credentials (POST)."""
    next_url = request.args.get("next") or request.form.get("next")

    if request.method == "GET":
        return render_template("admin/login.html", next=next_url, error=None)

    email = (request.form.get("email") or "").strip().lower()
    password = request.form.get("password") or ""

    if not email or not password:
        return (
            render_template(
                "admin/login.html",
                next=next_url,
                error="Email and password are required.",
            ),
            400,
        )

    with get_session() as session:
        user = User.get_active_by_email(session, email)
        # Always run verify_password (or a dummy) to avoid timing oracles
        # that would let an attacker enumerate registered emails.
        if user is None:
            User.hash_password("dummy-to-equalize-timing")  # discard
            current_app.logger.info("auth.login: unknown email %s", email)
            return (
                render_template(
                    "admin/login.html",
                    next=next_url,
                    error="Invalid email or password.",
                ),
                401,
            )

        if not user.verify_password(password):
            current_app.logger.info("auth.login: bad password for %s", email)
            return (
                render_template(
                    "admin/login.html",
                    next=next_url,
                    error="Invalid email or password.",
                ),
                401,
            )

        # Success. Update last_login_at + commit (verify_password may have
        # also opportunistically rehashed; both writes commit together).
        user.last_login_at = datetime.now(timezone.utc)
        session.add(user)
        session.flush()  # ensure UPDATE before login_user reads .id

        # remember=False: session cookie is session-scoped, not persistent.
        # Phase 4b can revisit if "remember me" is desired.
        login_user(user, remember=False)
        current_app.logger.info("auth.login: %s logged in (role=%s)", email, user.role)

    # Open-redirect-safe `next` handling.
    if next_url and _is_safe_redirect(next_url):
        return redirect(next_url)
    # Default landing: existing /admin index. Use raw URL since the admin
    # blueprint isn't owned by this module.
    return redirect("/admin")


@auth_bp.route("/logout", methods=["GET", "POST"])
@login_required
def logout() -> Response:
    """Clear the Flask-Login session and redirect to the login page."""
    logout_user()
    flash("Signed out.", "info")
    return redirect(url_for("auth.login"))


__all__ = ["auth_bp"]
