#!/usr/bin/env python3
"""Expand the wildprint catalog with missing US freshwater wildlife.

Adds ~70 new species (waterbirds, water snakes, fish, amphibians, plants)
to close significant ecological gaps in the 157-species catalog.
"""
from __future__ import annotations

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
SPECIES_PATH = DATA_DIR / "species" / "species.json"
PROFILES_PATH = DATA_DIR / "species" / "habitat_profiles.json"


def sp(common, slug, sci, cat, tags, traits, scale, ar, ranges, notes):
    return {
        "common_name": common,
        "slug": slug,
        "scientific_name": sci,
        "category": cat,
        "habitat_tags": tags,
        "key_visual_traits": traits,
        "relative_scale_index": scale,
        "enabled": True,
        "notes": notes,
        "target_aspect_ratio": ar,
        "geographic_range": ranges,
    }


def prof(wt, depth, flow, veg, clarity):
    return {
        "water_type": wt,
        "depth": depth,
        "flow": flow,
        "vegetation": veg,
        "clarity": clarity,
    }


# Common profile templates
DIVING_DUCK = prof(
    {"lake": 10, "pond": 4, "river": 5, "stream": 1, "reservoir": 9, "marsh": 3},
    {"shallow": 2, "moderate": 7, "deep": 10},
    {"still": 9, "slow": 7, "moderate": 4, "fast": 1},
    {"heavy": 2, "moderate": 4, "sparse": 7, "none": 9},
    {"clear": 8, "moderate": 7, "murky": 4},
)
COASTAL_SEADUCK = prof(
    {"lake": 3, "pond": 1, "river": 2, "stream": 1, "reservoir": 2, "marsh": 4},
    {"shallow": 3, "moderate": 8, "deep": 9},
    {"still": 6, "slow": 7, "moderate": 7, "fast": 4},
    {"heavy": 1, "moderate": 2, "sparse": 5, "none": 9},
    {"clear": 7, "moderate": 7, "murky": 5},
)
GREBE = prof(
    {"lake": 10, "pond": 7, "river": 4, "stream": 2, "reservoir": 9, "marsh": 7},
    {"shallow": 5, "moderate": 9, "deep": 8},
    {"still": 9, "slow": 7, "moderate": 3, "fast": 1},
    {"heavy": 5, "moderate": 7, "sparse": 6, "none": 5},
    {"clear": 8, "moderate": 7, "murky": 4},
)
MARSH_BIRD = prof(
    {"lake": 5, "pond": 7, "river": 4, "stream": 3, "reservoir": 5, "marsh": 10},
    {"shallow": 10, "moderate": 5, "deep": 1},
    {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
    {"heavy": 10, "moderate": 8, "sparse": 3, "none": 1},
    {"clear": 4, "moderate": 7, "murky": 8},
)
WADING_BIRD = prof(
    {"lake": 6, "pond": 8, "river": 6, "stream": 5, "reservoir": 6, "marsh": 10},
    {"shallow": 10, "moderate": 4, "deep": 1},
    {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
    {"heavy": 7, "moderate": 8, "sparse": 6, "none": 3},
    {"clear": 6, "moderate": 8, "murky": 7},
)
SHOREBIRD = prof(
    {"lake": 6, "pond": 7, "river": 6, "stream": 5, "reservoir": 5, "marsh": 9},
    {"shallow": 10, "moderate": 3, "deep": 1},
    {"still": 8, "slow": 8, "moderate": 5, "fast": 2},
    {"heavy": 5, "moderate": 7, "sparse": 8, "none": 7},
    {"clear": 6, "moderate": 8, "murky": 6},
)
TERN_GULL = prof(
    {"lake": 9, "pond": 5, "river": 7, "stream": 3, "reservoir": 8, "marsh": 6},
    {"shallow": 7, "moderate": 8, "deep": 6},
    {"still": 7, "slow": 7, "moderate": 6, "fast": 3},
    {"heavy": 2, "moderate": 4, "sparse": 7, "none": 9},
    {"clear": 8, "moderate": 7, "murky": 5},
)
SWAN = prof(
    {"lake": 10, "pond": 8, "river": 6, "stream": 2, "reservoir": 7, "marsh": 9},
    {"shallow": 9, "moderate": 7, "deep": 3},
    {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
    {"heavy": 8, "moderate": 9, "sparse": 5, "none": 3},
    {"clear": 7, "moderate": 7, "murky": 5},
)
MARSH_SONGBIRD = prof(
    {"lake": 4, "pond": 6, "river": 4, "stream": 4, "reservoir": 4, "marsh": 10},
    {"shallow": 9, "moderate": 4, "deep": 1},
    {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
    {"heavy": 10, "moderate": 8, "sparse": 3, "none": 1},
    {"clear": 5, "moderate": 7, "murky": 7},
)
WATER_SNAKE = prof(
    {"lake": 7, "pond": 8, "river": 8, "stream": 8, "reservoir": 6, "marsh": 9},
    {"shallow": 10, "moderate": 6, "deep": 2},
    {"still": 8, "slow": 9, "moderate": 5, "fast": 2},
    {"heavy": 8, "moderate": 9, "sparse": 6, "none": 3},
    {"clear": 6, "moderate": 8, "murky": 7},
)
COTTONMOUTH_PROF = prof(
    {"lake": 5, "pond": 8, "river": 6, "stream": 6, "reservoir": 4, "marsh": 10},
    {"shallow": 10, "moderate": 5, "deep": 1},
    {"still": 10, "slow": 8, "moderate": 2, "fast": 1},
    {"heavy": 10, "moderate": 7, "sparse": 3, "none": 1},
    {"clear": 3, "moderate": 6, "murky": 9},
)
QUEEN_SNAKE_PROF = prof(
    {"lake": 3, "pond": 3, "river": 8, "stream": 10, "reservoir": 3, "marsh": 2},
    {"shallow": 10, "moderate": 5, "deep": 1},
    {"still": 3, "slow": 7, "moderate": 9, "fast": 6},
    {"heavy": 5, "moderate": 7, "sparse": 7, "none": 4},
    {"clear": 9, "moderate": 7, "murky": 3},
)
FISH_BIG_RIVER = prof(
    {"lake": 7, "pond": 4, "river": 10, "stream": 6, "reservoir": 7, "marsh": 3},
    {"shallow": 4, "moderate": 9, "deep": 8},
    {"still": 4, "slow": 8, "moderate": 8, "fast": 5},
    {"heavy": 4, "moderate": 6, "sparse": 7, "none": 5},
    {"clear": 5, "moderate": 8, "murky": 7},
)
FISH_STREAM_SMALL = prof(
    {"lake": 4, "pond": 4, "river": 8, "stream": 10, "reservoir": 3, "marsh": 4},
    {"shallow": 10, "moderate": 6, "deep": 2},
    {"still": 5, "slow": 8, "moderate": 8, "fast": 5},
    {"heavy": 7, "moderate": 8, "sparse": 6, "none": 3},
    {"clear": 8, "moderate": 7, "murky": 4},
)
KILLIFISH_PROF = prof(
    {"lake": 5, "pond": 8, "river": 5, "stream": 6, "reservoir": 3, "marsh": 10},
    {"shallow": 10, "moderate": 4, "deep": 1},
    {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
    {"heavy": 9, "moderate": 8, "sparse": 4, "none": 2},
    {"clear": 5, "moderate": 8, "murky": 7},
)
PICKEREL_PROF = prof(
    {"lake": 7, "pond": 9, "river": 6, "stream": 7, "reservoir": 6, "marsh": 8},
    {"shallow": 9, "moderate": 6, "deep": 2},
    {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
    {"heavy": 10, "moderate": 8, "sparse": 4, "none": 2},
    {"clear": 6, "moderate": 8, "murky": 6},
)
EEL_PROF = prof(
    {"lake": 5, "pond": 4, "river": 10, "stream": 8, "reservoir": 5, "marsh": 6},
    {"shallow": 6, "moderate": 9, "deep": 7},
    {"still": 5, "slow": 9, "moderate": 7, "fast": 3},
    {"heavy": 7, "moderate": 8, "sparse": 5, "none": 3},
    {"clear": 4, "moderate": 7, "murky": 8},
)
SALMON_PROF = prof(
    {"lake": 6, "pond": 2, "river": 10, "stream": 9, "reservoir": 3, "marsh": 1},
    {"shallow": 6, "moderate": 9, "deep": 7},
    {"still": 2, "slow": 6, "moderate": 9, "fast": 8},
    {"heavy": 2, "moderate": 5, "sparse": 7, "none": 7},
    {"clear": 9, "moderate": 7, "murky": 3},
)
BUFFALO_PROF = prof(
    {"lake": 8, "pond": 6, "river": 10, "stream": 5, "reservoir": 9, "marsh": 6},
    {"shallow": 4, "moderate": 8, "deep": 8},
    {"still": 5, "slow": 9, "moderate": 7, "fast": 2},
    {"heavy": 5, "moderate": 7, "sparse": 6, "none": 4},
    {"clear": 3, "moderate": 7, "murky": 9},
)
AMPHIBIAN_FROG = prof(
    {"lake": 6, "pond": 9, "river": 5, "stream": 6, "reservoir": 5, "marsh": 10},
    {"shallow": 10, "moderate": 4, "deep": 1},
    {"still": 9, "slow": 8, "moderate": 2, "fast": 1},
    {"heavy": 10, "moderate": 8, "sparse": 4, "none": 2},
    {"clear": 6, "moderate": 8, "murky": 6},
)
SIREN_PROF = prof(
    {"lake": 5, "pond": 9, "river": 4, "stream": 4, "reservoir": 3, "marsh": 10},
    {"shallow": 10, "moderate": 5, "deep": 1},
    {"still": 10, "slow": 7, "moderate": 1, "fast": 1},
    {"heavy": 10, "moderate": 7, "sparse": 3, "none": 1},
    {"clear": 3, "moderate": 6, "murky": 9},
)
PLANT_SHALLOW = prof(
    {"lake": 7, "pond": 9, "river": 5, "stream": 4, "reservoir": 6, "marsh": 10},
    {"shallow": 10, "moderate": 5, "deep": 1},
    {"still": 10, "slow": 7, "moderate": 2, "fast": 1},
    {"heavy": 10, "moderate": 8, "sparse": 3, "none": 1},
    {"clear": 6, "moderate": 8, "murky": 6},
)
PLANT_EMERGENT = prof(
    {"lake": 5, "pond": 8, "river": 6, "stream": 7, "reservoir": 5, "marsh": 10},
    {"shallow": 10, "moderate": 4, "deep": 1},
    {"still": 8, "slow": 9, "moderate": 5, "fast": 2},
    {"heavy": 9, "moderate": 8, "sparse": 4, "none": 1},
    {"clear": 7, "moderate": 8, "murky": 5},
)


new_species = [
    # ---------- DIVING DUCKS ----------
    sp("Lesser Scaup", "lesser_scaup", "Aythya affinis", "bird",
       ["freshwater", "lakes", "ponds", "open water"],
       ["compact diving duck, body slightly longer than wide, proportions roughly 1.3:1 landscape",
        "male: black head with slight purple sheen, white sides, black chest and tail",
        "female: dark brown overall with white patch at base of bill",
        "distinctive peaked crown shape at the rear of the head",
        "pale blue-gray bill with a small black nail at the tip"],
       1.1, 1.4, ["nationwide"],
       "Most abundant diving duck in North America."),
    sp("Greater Scaup", "greater_scaup", "Aythya marila", "bird",
       ["freshwater", "saltwater", "lakes", "coastal"],
       ["stocky diving duck, body length about 1.4 times width, broad landscape profile",
        "male: black head with green sheen, white sides, black chest",
        "female: dark brown with bold white patch at bill base",
        "rounded head shape (not peaked like lesser scaup)",
        "broader blue-gray bill with black nail"],
       1.2, 1.4, ["alaska", "pacific_northwest", "northeast", "midwest"],
       "Slightly larger than lesser scaup; prefers larger, often coastal waters."),
    sp("Long-tailed Duck", "long_tailed_duck", "Clangula hyemalis", "bird",
       ["saltwater", "coastal", "open water"],
       ["slender sea duck, body proportions about 1.5:1 (excluding tail), elongated landscape profile with trailing tail streamers",
        "breeding male: bold black, white, and gray pattern with extremely long black tail plumes",
        "winter male: mostly white head and body with dark chest and back",
        "short stubby bill, pink band on male's bill",
        "small rounded head and compact body"],
       1.0, 1.8, ["alaska", "pacific_northwest", "northeast"],
       "Deep-diving sea duck of coastal and arctic waters."),
    sp("Harlequin Duck", "harlequin_duck", "Histrionicus histrionicus", "bird",
       ["freshwater", "saltwater", "rocky", "fast rivers"],
       ["small compact diving duck, body about 1.3:1 landscape, rounded profile",
        "male: slate blue body with bold white crescents and stripes outlined in black, chestnut flanks",
        "female: dark brown with three white spots on each side of the face",
        "small rounded head with short stubby bill",
        "short tail often held slightly cocked"],
       0.9, 1.3, ["pacific_northwest", "alaska", "northeast"],
       "Breeds on fast mountain streams, winters on rocky coasts."),
    sp("Surf Scoter", "surf_scoter", "Melanitta perspicillata", "bird",
       ["saltwater", "coastal", "open water"],
       ["stocky heavy-bodied sea duck, proportions about 1.4:1 landscape",
        "male: all black body with bold white patches on forehead and nape",
        "female: dark brown with two pale patches on each side of the face",
        "large swollen orange, white, and black bill on male",
        "thick neck and heavy build"],
       1.3, 1.4, ["alaska", "pacific_northwest", "northeast"],
       "Coastal sea duck; feeds on mollusks in surf zone."),
    sp("White-winged Scoter", "white_winged_scoter", "Melanitta deglandi", "bird",
       ["saltwater", "coastal", "open water", "lakes"],
       ["large heavy sea duck, body proportions about 1.5:1 landscape",
        "male: black body with distinctive white wing patch (speculum), white comma under eye",
        "female: dark brown with pale cheek patches and same white wing patch",
        "sloping forehead blending into a knobbed bill",
        "orange or yellowish bill with black base"],
       1.4, 1.5, ["alaska", "pacific_northwest", "northeast"],
       "Largest scoter; white wing patches are diagnostic in flight and at rest."),
    sp("Black Scoter", "black_scoter", "Melanitta americana", "bird",
       ["saltwater", "coastal", "open water"],
       ["compact round-bodied sea duck, proportions about 1.3:1 landscape",
        "male: entirely glossy black with bright yellow-orange knob at base of bill",
        "female: dark brown with pale cheeks contrasting with dark cap",
        "rounded head profile with steep forehead",
        "relatively small bill compared to other scoters"],
       1.2, 1.3, ["alaska", "pacific_northwest", "northeast"],
       "Only all-black North American duck; vocal on the water."),
    sp("Common Eider", "common_eider", "Somateria mollissima", "bird",
       ["saltwater", "coastal", "rocky"],
       ["very large heavy-bodied sea duck, body proportions about 1.6:1 landscape, bulky profile",
        "male: white back and chest, black belly and sides, black crown, pale green nape",
        "female: warm brown barred with black throughout",
        "long wedge-shaped bill extending smoothly from sloping forehead",
        "thick neck and heavy, goose-like build"],
       1.6, 1.5, ["alaska", "northeast"],
       "Largest duck in North America; breeds on arctic and north Atlantic coasts."),
    sp("Red-breasted Merganser", "red_breasted_merganser", "Mergus serrator", "bird",
       ["freshwater", "saltwater", "lakes", "coastal"],
       ["slender elongated diving duck, body proportions about 1.8:1 landscape, long-bodied",
        "male: dark green shaggy-crested head, rusty streaked breast, gray sides, white collar",
        "female: rusty-brown head with shaggy crest blending gradually into gray neck",
        "long thin serrated red-orange bill (sawbill)",
        "spiky double crest drooping from back of head"],
       1.2, 1.7, ["alaska", "pacific_northwest", "northeast", "midwest"],
       "Fish-eating sawbill; winters on coasts, breeds on northern lakes."),

    # ---------- GREBES ----------
    sp("Horned Grebe", "horned_grebe", "Podiceps auritus", "bird",
       ["freshwater", "saltwater", "lakes", "marshes"],
       ["small compact diving bird, body proportions about 1.3:1 landscape, no visible tail",
        "breeding: rufous neck and sides, black head with golden-yellow ear tufts (horns)",
        "winter: crisp black-and-white, white cheek sharply defined against black crown",
        "short straight dark bill with pale tip",
        "red eye visible at close range"],
       0.7, 1.3, ["alaska", "pacific_northwest", "mountain_west", "midwest", "northeast"],
       "Small grebe with dramatic breeding 'horns'."),
    sp("Eared Grebe", "eared_grebe", "Podiceps nigricollis", "bird",
       ["freshwater", "lakes", "marshes"],
       ["small slim diving bird, body proportions about 1.3:1 landscape",
        "breeding: black head and neck with wispy golden ear fans fanning back from eye",
        "winter: dusky cheek blending into dark crown (less crisp than horned grebe)",
        "slender slightly upturned thin dark bill",
        "peaked crown and red eye"],
       0.6, 1.3, ["mountain_west", "california", "southwest", "pacific_northwest"],
       "Most abundant grebe worldwide; forms huge staging flocks on alkaline lakes."),
    sp("Western Grebe", "western_grebe", "Aechmophorus occidentalis", "bird",
       ["freshwater", "lakes", "open water"],
       ["long-necked elegant diving bird, body proportions about 1.7:1 landscape including neck",
        "crisp black-and-white: black crown extends below red eye",
        "long slender swan-like neck, black above and white below",
        "long thin greenish-yellow dagger bill",
        "black back contrasting sharply with white flanks"],
       1.3, 1.7, ["pacific_northwest", "california", "mountain_west"],
       "Performs famous rushing courtship ceremony across water."),
    sp("Clark's Grebe", "clarks_grebe", "Aechmophorus clarkii", "bird",
       ["freshwater", "lakes", "open water"],
       ["long-necked elegant diving bird, body proportions about 1.7:1 landscape including neck",
        "near-identical to western grebe but black crown stops above eye (eye surrounded by white)",
        "bright orange-yellow bill (vs greenish-yellow in western)",
        "long slender neck white on the sides",
        "paler gray-black flanks"],
       1.3, 1.7, ["pacific_northwest", "california", "mountain_west"],
       "Formerly considered same species as western grebe."),
    sp("Red-necked Grebe", "red_necked_grebe", "Podiceps grisegena", "bird",
       ["freshwater", "saltwater", "lakes", "coastal"],
       ["medium stocky diving bird, body proportions about 1.4:1 landscape, thick-necked",
        "breeding: chestnut-red neck, pale gray cheek, black cap",
        "winter: dusky neck and crown, pale throat, yellowish bill base",
        "heavy straight yellow-based bill",
        "thicker neck than other grebes"],
       1.0, 1.4, ["alaska", "pacific_northwest", "northeast"],
       "Largest grebe besides western/Clark's; migratory across northern latitudes."),

    # ---------- RAILS / COOTS / GALLINULES ----------
    sp("American Coot", "american_coot", "Fulica americana", "bird",
       ["freshwater", "lakes", "ponds", "marshes"],
       ["plump dark waterbird, body proportions about 1.4:1 landscape, chicken-like build",
        "slate-gray to blackish body with darker head",
        "bright white chicken-like bill with small red spot near tip",
        "red eye and greenish lobed (not webbed) toes",
        "white undertail patches visible when tail is cocked"],
       1.0, 1.4, ["nationwide"],
       "Abundant; often mistaken for a duck but is a rail."),
    sp("Common Gallinule", "common_gallinule", "Gallinula galeata", "bird",
       ["freshwater", "marshes", "ponds", "weedy"],
       ["slim marsh bird with chicken-like body, proportions about 1.3:1 landscape",
        "slate-gray body with brownish back and bold white stripe along flank",
        "bright red frontal shield and red bill with yellow tip",
        "long yellow-green legs with unlobed long toes",
        "white undertail coverts flashing as tail flicks"],
       0.8, 1.3, ["southeast", "midwest", "northeast", "southwest", "california"],
       "Walks on floating vegetation in marshes."),
    sp("Sora", "sora", "Porzana carolina", "bird",
       ["freshwater", "marshes", "wetlands"],
       ["small compact rail, body proportions about 1.2:1, short-bodied with held-up tail",
        "grayish-brown body with black face mask and throat",
        "short stubby bright yellow bill",
        "barred black-and-white flanks and undertail",
        "greenish legs and long unwebbed toes"],
       0.5, 1.2, ["nationwide"],
       "Most common rail in North America; secretive."),
    sp("Virginia Rail", "virginia_rail", "Rallus limicola", "bird",
       ["freshwater", "marshes", "wetlands"],
       ["small slender rail, body proportions about 1.4:1 landscape, laterally compressed",
        "rusty-rufous breast, gray face, brown back streaked with black",
        "long slightly down-curved orange-red bill",
        "barred black-and-white flanks",
        "long reddish legs with unwebbed toes"],
       0.5, 1.3, ["nationwide"],
       "Thin body lets it slip through dense cattails."),
    sp("King Rail", "king_rail", "Rallus elegans", "bird",
       ["freshwater", "marshes", "wetlands"],
       ["large elongated rail, body proportions about 1.5:1 landscape, laterally compressed",
        "rich rusty breast and face, heavily striped brown-and-black back",
        "long slightly decurved yellowish bill",
        "bold black-and-white barred flanks",
        "long legs for wading through dense marsh"],
       0.9, 1.4, ["southeast", "midwest", "northeast", "southwest"],
       "Largest freshwater rail in North America."),
    sp("Purple Gallinule", "purple_gallinule", "Porphyrio martinica", "bird",
       ["freshwater", "marshes", "swamps", "weedy"],
       ["slim marsh bird with long toes, body proportions about 1.3:1 landscape",
        "iridescent purple head, neck, and breast with bronze-green back",
        "pale blue frontal shield, red bill with yellow tip",
        "extraordinarily long yellow toes for walking on lily pads",
        "white undertail coverts and yellow legs"],
       0.7, 1.3, ["southeast", "southwest"],
       "Tropical-looking marsh bird of southern wetlands."),

    # ---------- CRANES & WADING BIRDS ----------
    sp("Sandhill Crane", "sandhill_crane", "Antigone canadensis", "bird",
       ["freshwater", "marshes", "grasslands", "wetlands"],
       ["very tall slender crane, standing body proportions about 0.4:1 portrait, extremely long legs and neck",
        "gray body often stained rusty from iron-rich mud preening",
        "bare red crown patch from bill to behind eye",
        "long straight gray bill and white cheek patch",
        "bustle of drooping tertial feathers over the tail"],
       2.8, 0.4, ["nationwide"],
       "Widely distributed; massive migratory staging on the Platte River."),
    sp("Whooping Crane", "whooping_crane", "Grus americana", "bird",
       ["freshwater", "marshes", "wetlands", "coastal"],
       ["very tall white crane, standing body proportions about 0.4:1 portrait, extremely long legs and neck",
        "pure white plumage with black wingtips visible in flight",
        "bare red crown and face mask with dark mustache stripe",
        "long yellowish bill",
        "black legs, tallest bird in North America"],
       3.5, 0.4, ["southwest", "midwest"],
       "Endangered; single wild flock migrates Wood Buffalo to Aransas."),
    sp("Wood Stork", "wood_stork", "Mycteria americana", "bird",
       ["freshwater", "swamps", "marshes", "coastal"],
       ["large heavy wading bird, standing proportions about 0.5:1 portrait, bulky body on long legs",
        "white body with black flight feathers and tail",
        "bald dark gray scaly-skinned head and upper neck",
        "long heavy slightly down-curved dark bill",
        "pinkish feet contrasting with dark legs"],
       2.5, 0.5, ["southeast"],
       "Only native US stork; forages by tactile feeding in shallow water."),
    sp("Limpkin", "limpkin", "Aramus guarauna", "bird",
       ["freshwater", "marshes", "swamps"],
       ["tall brown wading bird, body proportions about 0.7:1 portrait, long-legged and long-necked",
        "warm chocolate-brown with bold white streaks and spots throughout",
        "long slightly down-curved grayish bill with slight gap near tip",
        "long dark legs and neck",
        "shaggy look from loose body feathers"],
       1.5, 0.7, ["southeast"],
       "Specializes on apple snails; loud wailing call at night."),
    sp("Roseate Spoonbill", "roseate_spoonbill", "Platalea ajaja", "bird",
       ["freshwater", "saltwater", "marshes", "coastal"],
       ["medium-large wading bird, body proportions about 0.6:1 portrait, long legs, medium neck",
        "brilliant pink body with deeper pink wing patches and orange tail",
        "bald pale green head with dark band across nape",
        "long flattened gray spoon-shaped bill",
        "red legs and red shoulder patch"],
       1.7, 0.6, ["southeast"],
       "Unique spatulate bill swept side-to-side to catch prey."),
    sp("Anhinga", "anhinga", "Anhinga anhinga", "bird",
       ["freshwater", "swamps", "marshes", "lakes"],
       ["long slender waterbird, body proportions about 0.8:1 portrait, extremely long neck and tail",
        "male: glossy black with silvery-white streaks on wings and back",
        "female: buffy tan neck and breast, dark belly",
        "long pointed yellow dagger bill (no hook)",
        "long fan-shaped tail, often perches with wings spread to dry"],
       1.7, 0.8, ["southeast"],
       "Snakebird; swims with only neck above water."),
    sp("Brown Pelican", "brown_pelican", "Pelecanus occidentalis", "bird",
       ["saltwater", "coastal", "open water"],
       ["massive heavy-bodied bird, body proportions about 1.2:1 landscape, enormous bill pouch",
        "gray-brown body with white head and neck (breeding: dark chestnut nape)",
        "enormous gray bill with expandable throat pouch",
        "short dark legs with fully webbed feet",
        "plunge-dives from the air (unlike white pelican)"],
       2.5, 1.2, ["southeast"],
       "Atlantic and Gulf Coast specialist; plunge-diver."),
    sp("Reddish Egret", "reddish_egret", "Egretta rufescens", "bird",
       ["saltwater", "coastal", "marshes"],
       ["slender medium heron, standing proportions about 0.5:1 portrait, long legs and neck",
        "dark morph: slate-gray body with rusty shaggy head and neck",
        "white morph: all white plumage",
        "pink bill with black tip, blue-gray legs",
        "active 'dancing' foraging style with canopy feeding"],
       1.4, 0.5, ["southeast", "southwest"],
       "Least common US heron; famous for active erratic foraging."),

    # ---------- SWANS ----------
    sp("Trumpeter Swan", "trumpeter_swan", "Cygnus buccinator", "bird",
       ["freshwater", "lakes", "marshes", "rivers"],
       ["huge long-necked waterbird, body proportions about 1.5:1 landscape, extremely long neck",
        "pure white plumage with black bill and black facial skin",
        "straight black bill extending in a straight line from the forehead",
        "thick, heavy black legs",
        "largest native waterfowl in North America"],
       3.5, 1.5, ["alaska", "pacific_northwest", "mountain_west", "midwest"],
       "Largest waterfowl in US; recovered from near-extinction."),
    sp("Tundra Swan", "tundra_swan", "Cygnus columbianus", "bird",
       ["freshwater", "lakes", "marshes"],
       ["large long-necked waterbird, body proportions about 1.4:1 landscape",
        "pure white plumage with black bill",
        "black bill usually with a small yellow spot in front of the eye",
        "slightly concave profile between forehead and bill",
        "smaller than trumpeter, more rounded head"],
       2.8, 1.4, ["alaska", "pacific_northwest", "northeast", "midwest"],
       "Whistling swan; breeds in arctic, winters south."),
    sp("Mute Swan", "mute_swan", "Cygnus olor", "bird",
       ["freshwater", "lakes", "ponds"],
       ["large long-necked waterbird, body proportions about 1.4:1 landscape, often holds neck in S-curve",
        "pure white plumage with orange bill",
        "orange bill with prominent black basal knob (larger in males)",
        "often holds wings arched over back in display",
        "neck typically held in graceful S-curve"],
       2.8, 1.4, ["northeast", "midwest", "pacific_northwest"],
       "Introduced from Europe; aggressive and locally invasive."),

    # ---------- SHOREBIRDS ----------
    sp("Killdeer", "killdeer", "Charadrius vociferus", "bird",
       ["freshwater", "shorelines", "grasslands", "mudflats"],
       ["compact plover with long tail for its family, body proportions about 1.3:1 landscape",
        "brown back, white underparts, two bold black breast bands",
        "bright orange-red rump visible in flight and display",
        "large dark eye with red eyering",
        "long wings and tail compared to other plovers"],
       0.5, 1.2, ["nationwide"],
       "Most familiar plover; performs broken-wing distraction display."),
    sp("Spotted Sandpiper", "spotted_sandpiper", "Actitis macularius", "bird",
       ["freshwater", "shorelines", "streams", "mudflats"],
       ["small compact sandpiper, body proportions about 1.3:1 landscape, constantly teetering",
        "breeding: bold round dark spots across white underparts",
        "winter: plain white underparts, olive-brown back",
        "orange-pink bill with dark tip (breeding)",
        "white 'shoulder' notch where wing meets breast"],
       0.3, 1.2, ["nationwide"],
       "Constantly bobs and teeters along shorelines."),
    sp("Wilson's Snipe", "wilsons_snipe", "Gallinago delicata", "bird",
       ["freshwater", "marshes", "wetlands"],
       ["stocky compact shorebird, body proportions about 1.3:1 landscape, very long bill",
        "cryptic brown, buff, and black striped and barred plumage",
        "extremely long straight bill (about 1.5x head length)",
        "bold buff stripes on head and back",
        "short orange legs, often crouched low"],
       0.5, 1.3, ["nationwide"],
       "Cryptic marsh bird; aerial 'winnowing' courtship display."),
    sp("American Woodcock", "american_woodcock", "Scolopax minor", "bird",
       ["freshwater", "wet woodlands", "thickets"],
       ["plump football-shaped shorebird, body proportions about 1.2:1 landscape, almost no tail",
        "cryptic mottled rusty, brown, and black woodland camouflage",
        "very long straight bill (flexible-tipped for probing)",
        "large dark eyes set high and far back on head",
        "very short legs and short tail"],
       0.5, 1.1, ["northeast", "midwest", "southeast"],
       "Timberdoodle; twilight sky-dance courtship."),
    sp("Greater Yellowlegs", "greater_yellowlegs", "Tringa melanoleuca", "bird",
       ["freshwater", "saltwater", "marshes", "mudflats"],
       ["slender tall sandpiper, body proportions about 1.1:1, long-legged with long neck",
        "gray-brown finely streaked upperparts, white underparts with streaked breast",
        "long bright yellow legs",
        "long slightly upturned bill (longer than head)",
        "white rump visible in flight"],
       0.7, 1.1, ["nationwide"],
       "Noisy 'tattler' of open wetlands during migration."),

    # ---------- TERNS / GULLS ----------
    sp("Ring-billed Gull", "ring_billed_gull", "Larus delawarensis", "bird",
       ["freshwater", "saltwater", "lakes", "coastal"],
       ["medium gull, body proportions about 1.5:1 landscape",
        "pale gray back, white head and underparts (winter: streaked nape)",
        "yellow bill with distinct black ring near the tip",
        "yellow legs and pale eye",
        "black wingtips with small white spots (mirrors)"],
       1.0, 1.5, ["nationwide"],
       "Most common inland gull across continent."),
    sp("Common Tern", "common_tern", "Sterna hirundo", "bird",
       ["freshwater", "saltwater", "lakes", "coastal"],
       ["slender graceful tern, body proportions about 1.7:1 landscape",
        "pale gray back and wings, white underparts",
        "black cap extending to nape, red-orange bill with black tip",
        "deeply forked white tail",
        "orange-red legs"],
       0.7, 1.6, ["northeast", "midwest", "pacific_northwest", "california"],
       "Widespread tern of lakes and coasts."),
    sp("Forster's Tern", "forsters_tern", "Sterna forsteri", "bird",
       ["freshwater", "saltwater", "marshes", "coastal"],
       ["slender graceful tern, body proportions about 1.7:1 landscape",
        "pale gray back, very pale silvery-white primaries",
        "black cap (breeding) or black ear patch only (winter)",
        "orange bill with black tip (breeding)",
        "longer deeply forked white tail"],
       0.7, 1.6, ["nationwide"],
       "Marsh tern of North America; winter has diagnostic black eye patch."),
    sp("Black Tern", "black_tern", "Chlidonias niger", "bird",
       ["freshwater", "marshes", "lakes"],
       ["small slender tern, body proportions about 1.6:1 landscape, buoyant flight",
        "breeding: black head and underparts with gray back and wings",
        "non-breeding: white underparts with black ear patch and crown",
        "thin black bill",
        "short slightly forked tail and dark legs"],
       0.5, 1.5, ["midwest", "mountain_west", "northeast", "pacific_northwest"],
       "Marsh-nesting tern; only small dark tern in North America."),
    sp("Caspian Tern", "caspian_tern", "Hydroprogne caspia", "bird",
       ["freshwater", "saltwater", "lakes", "coastal"],
       ["large gull-sized tern, body proportions about 1.5:1 landscape",
        "pale gray back, white underparts",
        "huge thick blood-red bill (largest tern bill)",
        "black cap (breeding) or streaked black crown (winter)",
        "shallowly forked tail and black legs"],
       1.1, 1.5, ["nationwide"],
       "Largest tern in the world; harsh grating call."),

    # ---------- MARSH SONGBIRDS ----------
    sp("Red-winged Blackbird", "red_winged_blackbird", "Agelaius phoeniceus", "bird",
       ["freshwater", "marshes", "wetlands"],
       ["medium blackbird, body proportions about 1.3:1 landscape",
        "male: glossy black with brilliant red shoulder patch bordered with yellow",
        "female: streaky brown sparrow-like appearance",
        "pointed conical black bill",
        "often perches on cattails and reeds singing 'conk-a-ree'"],
       0.3, 1.2, ["nationwide"],
       "One of the most abundant birds in North America."),
    sp("Yellow-headed Blackbird", "yellow_headed_blackbird", "Xanthocephalus xanthocephalus", "bird",
       ["freshwater", "marshes", "wetlands"],
       ["medium blackbird, body proportions about 1.3:1 landscape",
        "male: bold yellow head and breast on black body with white wing patch",
        "female: duskier brown with pale yellow throat and face",
        "sharp black conical bill",
        "nests in deep-water marshes west of Mississippi"],
       0.4, 1.3, ["midwest", "mountain_west", "southwest", "california", "pacific_northwest"],
       "Displaces red-winged blackbirds from best marsh territories."),
    sp("Marsh Wren", "marsh_wren", "Cistothorus palustris", "bird",
       ["freshwater", "marshes", "cattails"],
       ["tiny compact wren, body proportions about 1.1:1, stubby and rounded",
        "rich rusty-brown back with bold white streaks on upper back",
        "warm buffy flanks, whitish throat and belly",
        "bold white eyebrow stripe over dark crown",
        "short tail often cocked up over back"],
       0.2, 1.1, ["nationwide"],
       "Tiny but loud; males build many dummy nests."),
    sp("Prothonotary Warbler", "prothonotary_warbler", "Protonotaria citrea", "bird",
       ["freshwater", "swamps", "wet forests"],
       ["small compact warbler, body proportions about 1.2:1 landscape",
        "brilliant golden-yellow head and underparts",
        "blue-gray wings and tail with no wing bars",
        "olive-green back",
        "relatively long sharp black bill and dark eye"],
       0.2, 1.1, ["southeast", "midwest", "northeast"],
       "Only cavity-nesting warbler in the east; swamp specialist."),
    sp("Tree Swallow", "tree_swallow", "Tachycineta bicolor", "bird",
       ["freshwater", "marshes", "open water"],
       ["small streamlined swallow, body proportions about 1.6:1 landscape, long pointed wings",
        "iridescent blue-green upperparts, clean white underparts",
        "short notched tail",
        "short flat triangular black bill",
        "white extends just above the eye (not through it)"],
       0.2, 1.5, ["nationwide"],
       "Hawks insects low over water; nests in tree cavities and boxes."),

    # ---------- REPTILES: WATER SNAKES + COTTONMOUTH ----------
    sp("Northern Water Snake", "northern_water_snake", "Nerodia sipedon", "reptile",
       ["freshwater", "lakes", "rivers", "marshes"],
       ["long slender nonvenomous snake, body length about 15-20 times body width, elongated tube profile",
        "dark brown to gray with reddish-brown crossbands on the neck that break into blotches behind",
        "pattern becomes darker and more obscured with age",
        "keeled scales giving a rough appearance",
        "round pupils and no facial pit (unlike cottonmouth)"],
       2.0, 5.5, ["northeast", "midwest", "southeast"],
       "Most widespread water snake; often confused with cottonmouth."),
    sp("Brown Water Snake", "brown_water_snake", "Nerodia taxispilota", "reptile",
       ["freshwater", "rivers", "swamps", "lakes"],
       ["heavy-bodied nonvenomous snake, body length about 14-18 times body width, thick elongated profile",
        "rich brown with three rows of darker square blotches alternating along the back and sides",
        "pale belly heavily marked with dark blotches",
        "narrow neck contrasting with thick body and squarish head",
        "keeled scales and round pupils"],
       2.0, 5.5, ["southeast"],
       "Large heavy southern river specialist; excellent basker."),
    sp("Banded Water Snake", "banded_water_snake", "Nerodia fasciata", "reptile",
       ["freshwater", "swamps", "marshes", "ponds"],
       ["long slender nonvenomous snake, body length about 15-20 times body width, elongated tube profile",
        "tan to gray background with dark reddish-brown to black complete crossbands down the back",
        "dark stripe from eye to angle of jaw",
        "yellowish belly with dark squarish spots",
        "round pupils and keeled scales"],
       1.8, 5.5, ["southeast", "southwest"],
       "Often confused with cottonmouth; harmless but bites when handled."),
    sp("Diamondback Water Snake", "diamondback_water_snake", "Nerodia rhombifer", "reptile",
       ["freshwater", "rivers", "swamps", "lakes"],
       ["heavy-bodied nonvenomous snake, body length about 14-18 times body width, thick elongated profile",
        "brown to olive with a dark chain-like diamond pattern down the back",
        "yellow belly with half-moon-shaped dark markings",
        "heavily keeled scales and squarish head",
        "largest water snake in the genus Nerodia"],
       2.1, 5.5, ["southwest", "southeast"],
       "Largest North American water snake; often seen dangling from branches."),
    sp("Plain-bellied Water Snake", "plain_bellied_water_snake", "Nerodia erythrogaster", "reptile",
       ["freshwater", "swamps", "ponds", "rivers"],
       ["long slender nonvenomous snake, body length about 15-20 times body width, elongated tube profile",
        "uniform olive, gray, brown, or greenish-black dorsum with no dorsal pattern in adults",
        "unmarked plain yellow, orange, or red belly (diagnostic)",
        "round pupils and keeled scales",
        "juveniles have reddish crossbands that fade with age"],
       1.9, 5.5, ["southeast", "southwest", "midwest"],
       "Wanders widely overland between wetlands."),
    sp("Cottonmouth", "cottonmouth", "Agkistrodon piscivorus", "reptile",
       ["freshwater", "swamps", "marshes", "slow rivers"],
       ["heavy thick-bodied venomous pit viper, body length about 8-10 times body width, stout elongated profile",
        "dark olive-brown to black with obscure dark crossbands that fade with age",
        "broad angular triangular head distinctly wider than neck",
        "vertical cat-like pupils and heat-sensing pit between eye and nostril",
        "gapes to show stark white mouth lining as threat display"],
       2.5, 5.0, ["southeast", "southwest"],
       "Only venomous water snake in US; sluggish but will stand its ground."),
    sp("Queen Snake", "queen_snake", "Regina septemvittata", "reptile",
       ["freshwater", "streams", "rivers", "rocky"],
       ["slender small nonvenomous snake, body length about 18-22 times body width, very elongated profile",
        "olive-brown to gray-brown dorsum with a pale yellow stripe low on each side",
        "cream-yellow belly with four brown stripes down its length",
        "keeled scales and round pupils",
        "narrow head, specializes on freshly molted crayfish"],
       1.0, 6.0, ["midwest", "northeast", "southeast"],
       "Crayfish specialist of clean rocky streams."),

    # ---------- FISH ----------
    sp("American Eel", "american_eel", "Anguilla rostrata", "fish",
       ["freshwater", "brackish", "rivers", "streams"],
       ["extremely elongated snake-like fish, body length about 15-20 times body depth, nearly cylindrical",
        "yellow-brown to olive back fading to yellowish belly (yellow phase) or silvery (migratory silver phase)",
        "long dorsal fin continuous with caudal and anal fins forming a single fringe along posterior half",
        "no pelvic fins, small rounded pectoral fins just behind gill",
        "lower jaw projects slightly beyond upper"],
       2.0, 10.0, ["northeast", "southeast", "midwest"],
       "Catadromous; spawns in Sargasso Sea, matures in freshwater."),
    sp("Chum Salmon", "chum_salmon", "Oncorhynchus keta", "fish",
       ["freshwater", "saltwater", "rivers", "ocean"],
       ["robust elongated salmon, body length about 4-5 times body depth, classic torpedo profile",
        "ocean phase: silver with small black speckles on back, no spots on tail",
        "spawning male: olive-green with purplish vertical bars ('calico' pattern) and hooked jaw",
        "spawning female: duller with dark horizontal stripe",
        "large pupil nearly filling the eye"],
       2.3, 3.5, ["alaska", "pacific_northwest"],
       "Dog salmon; second-largest Pacific salmon by size."),
    sp("Redfin Pickerel", "redfin_pickerel", "Esox americanus americanus", "fish",
       ["freshwater", "swamps", "backwaters", "weedy"],
       ["elongated pike-shaped body, body length about 5-6 times body depth, narrow streamlined profile",
        "olive back with golden flanks marked with dark wavy vertical bars",
        "distinctive red-orange lower fins (redfin)",
        "duckbill-shaped snout shorter than grass pickerel's",
        "dark vertical teardrop bar below the eye"],
       0.6, 4.5, ["northeast", "southeast"],
       "Small colorful pickerel of eastern blackwater streams."),
    sp("Grass Pickerel", "grass_pickerel", "Esox americanus vermiculatus", "fish",
       ["freshwater", "ponds", "backwaters", "weedy"],
       ["elongated pike-shaped body, body length about 5-6 times body depth, narrow streamlined profile",
        "olive-brown back with golden sides marked with chain-like dark wavy bars",
        "pale yellow-green lower fins (not red)",
        "dark vertical teardrop bar below eye",
        "short duckbill snout with many sharp teeth"],
       0.6, 4.5, ["midwest", "northeast", "southeast"],
       "Western subspecies of redfin pickerel; drab fin colors."),
    sp("Bigmouth Buffalo", "bigmouth_buffalo", "Ictiobus cyprinellus", "fish",
       ["freshwater", "rivers", "lakes"],
       ["large deep-bodied sucker, body length about 2.5-3 times body depth, robust oval profile",
        "dull olive-bronze to coppery gray with darker back",
        "large terminal upward-angled mouth (unlike downturned sucker mouth)",
        "long sickle-shaped dorsal fin with tall leading rays",
        "small eye and large head"],
       2.5, 2.7, ["midwest", "southeast", "southwest"],
       "Filter-feeds on plankton; one of longest-lived fish (100+ years)."),
    sp("Johnny Darter", "johnny_darter", "Etheostoma nigrum", "fish",
       ["freshwater", "streams", "rivers", "rocky"],
       ["small slender darter, body length about 5-6 times body depth, elongated cigar profile",
        "pale sand-colored body with dark W-, X-, or M-shaped marks along sides",
        "large eyes high on head",
        "two dorsal fins (spiny and soft) close together",
        "rests on bottom propped up on large pectoral fins"],
       0.2, 4.5, ["midwest", "northeast", "southeast"],
       "Most widespread darter; clean gravel streams."),
    sp("Rainbow Darter", "rainbow_darter", "Etheostoma caeruleum", "fish",
       ["freshwater", "streams", "rocky"],
       ["small slender darter, body length about 5-6 times body depth, elongated profile",
        "breeding male: brilliant alternating bright blue and red-orange vertical bars on sides",
        "female: pale olive with subtle brownish bars",
        "orange belly in breeding males",
        "two dorsal fins and bold-eyed profile"],
       0.2, 4.5, ["midwest", "southeast", "northeast"],
       "Among the most colorful freshwater fish in North America."),
    sp("Common Shiner", "common_shiner", "Luxilus cornutus", "fish",
       ["freshwater", "streams", "rivers"],
       ["slender streamlined minnow, body length about 3.5-4 times body depth, laterally compressed",
        "silvery sides with dusky olive back and faint dark lateral line",
        "breeding male: rosy pink fins and head with prominent tubercles (bumps)",
        "large scales on flanks with dark crescent edges",
        "terminal slightly upturned mouth"],
       0.3, 3.8, ["northeast", "midwest", "southeast"],
       "Common stream minnow; males become gaudy in spring."),
    sp("Golden Shiner", "golden_shiner", "Notemigonus crysoleucas", "fish",
       ["freshwater", "ponds", "lakes", "weedy"],
       ["deep-bodied slab-sided minnow, body length about 2.5-3 times body depth, laterally compressed",
        "golden or brassy sides with olive back",
        "small upturned mouth and arched back",
        "scaleless keel along belly between pelvic fins and anus (diagnostic)",
        "deeply forked tail"],
       0.3, 3.0, ["nationwide"],
       "Widely used as a bait minnow; tolerant of poor water."),
    sp("Fathead Minnow", "fathead_minnow", "Pimephales promelas", "fish",
       ["freshwater", "ponds", "streams", "weedy"],
       ["small chubby minnow, body length about 3.5-4 times body depth, stout profile",
        "olive-brown back fading to pale silvery belly",
        "dusky mid-lateral stripe and dark blotch at front of dorsal fin",
        "blunt rounded head with small upturned mouth",
        "breeding male: jet black head with white tubercles and fleshy back pad"],
       0.2, 3.5, ["nationwide"],
       "Ubiquitous baitfish and toxicity-testing model organism."),
    sp("Banded Killifish", "banded_killifish", "Fundulus diaphanus", "fish",
       ["freshwater", "brackish", "ponds", "weedy"],
       ["elongated cylindrical topminnow, body length about 4-5 times body depth, slightly flattened above",
        "silvery-olive body with 12-20 thin dark vertical bars along the sides",
        "flat-topped head and upturned mouth for surface feeding",
        "dorsal fin set far back on the body",
        "rounded caudal fin"],
       0.3, 4.0, ["northeast", "midwest"],
       "Only native freshwater killifish in much of the Northeast."),
    sp("Mummichog", "mummichog", "Fundulus heteroclitus", "fish",
       ["brackish", "saltwater", "marshes", "estuaries"],
       ["stocky stout topminnow, body length about 3.5-4 times body depth, chunky profile",
        "male: olive-green with silvery vertical bars and yellow belly in breeding season",
        "female: plain olive-brown with faint darker mottling",
        "flat-topped head and upturned mouth",
        "rounded caudal fin and blunt body shape"],
       0.25, 3.5, ["northeast", "southeast"],
       "Tolerant estuarine killifish; survives extreme salinity and temperature."),

    # ---------- AMPHIBIANS ----------
    sp("Pickerel Frog", "pickerel_frog", "Lithobates palustris", "amphibian",
       ["freshwater", "streams", "marshes", "wet forests"],
       ["medium slim true frog, body proportions about 1.5:1 landscape when sitting, long legs folded",
        "tan to bronze dorsum with two parallel rows of squarish dark brown spots (chocolate bars)",
        "bright yellow or orange wash on the underside of thighs (flash colors)",
        "prominent dorsolateral ridges running length of back",
        "pointed snout and bronze-colored eye"],
       0.3, 1.4, ["northeast", "midwest", "southeast"],
       "Skin secretions toxic to other amphibians; clean cool water."),
    sp("Mink Frog", "mink_frog", "Lithobates septentrionalis", "amphibian",
       ["freshwater", "lakes", "bogs"],
       ["medium stocky true frog, body proportions about 1.4:1 landscape when sitting",
        "green to olive-brown dorsum irregularly mottled with dark blotches (not bars)",
        "skin smells like mink or rotten onions when handled",
        "fully webbed hind feet (more webbed than bullfrog)",
        "no dorsolateral ridges; dark spots spill onto yellowish belly"],
       0.4, 1.4, ["northeast"],
       "Northernmost US ranid; bogs and northern lakes."),
    sp("Barking Treefrog", "barking_treefrog", "Hyla gratiosa", "amphibian",
       ["freshwater", "ponds", "swamps"],
       ["large chunky treefrog, body proportions about 1.2:1 landscape, granular skin",
        "bright green to brownish with many dark round spots scattered over the back",
        "white to yellow stripe along upper lip and side",
        "largest native US treefrog (up to 7 cm)",
        "large sticky toe pads and granular bumpy skin"],
       0.2, 1.2, ["southeast"],
       "Loud dog-like barking call from high in trees."),
    sp("Greater Siren", "greater_siren", "Siren lacertina", "amphibian",
       ["freshwater", "swamps", "marshes", "weedy"],
       ["enormous eel-like salamander, body length about 15-20 times body depth, extremely elongated",
        "olive-gray to dark brown with faint greenish or yellowish flecks",
        "external feathery red gills behind head (neotenic, kept for life)",
        "only two small front legs with four toes; no hind legs",
        "long laterally compressed tail with a dorsal fin"],
       1.5, 10.0, ["southeast"],
       "One of largest salamanders in the world; fully aquatic."),
    sp("Two-toed Amphiuma", "two_toed_amphiuma", "Amphiuma means", "amphibian",
       ["freshwater", "swamps", "marshes", "muddy"],
       ["long eel-like salamander, body length about 18-25 times body depth, extremely elongated cylindrical",
        "uniform dark slate-gray to blackish above, slightly paler below",
        "four vestigial tiny legs, each with two toes (diagnostic)",
        "no external gills; has gill slit but breathes air",
        "small eyes without eyelids and broad flattened head"],
       1.8, 12.0, ["southeast"],
       "Congo eel; can inflict serious bite when handled."),

    # ---------- PLANTS ----------
    sp("Watershield", "watershield", "Brasenia schreberi", "plant",
       ["freshwater", "ponds", "lakes", "still water"],
       ["small floating-leaved aquatic plant, leaves about 1.5:1 oval landscape",
        "small oval floating leaves 5-10 cm with central petiole attachment (like miniature lily)",
        "leaves dark green above, reddish-purple below",
        "entire plant (underside of leaves, stems, buds) coated in thick clear jelly",
        "small dull purple flowers held just above water"],
       0.1, 1.5, ["nationwide"],
       "Floating leaves in soft-water ponds; characteristic gelatinous coating."),
    sp("Water Willow", "water_willow", "Justicia americana", "plant",
       ["freshwater", "streams", "rivers", "rocky"],
       ["emergent streamside herb, colonies about 0.4:1 portrait with erect stems",
        "lance-shaped opposite willow-like leaves along erect stems",
        "grows in dense colonies from rhizomes in shallow flowing water",
        "small orchid-like white flowers with purple markings in compact clusters",
        "stems 30-80 cm tall emergent above water"],
       0.4, 0.5, ["midwest", "northeast", "southeast"],
       "Dominant emergent plant of rocky stream margins in the east."),
    sp("Yellow Water Lily", "yellow_water_lily", "Nuphar advena", "plant",
       ["freshwater", "ponds", "slow rivers", "marshes"],
       ["large floating-leaved aquatic, leaves about 1.2:1 nearly round",
        "large heart-shaped to oval floating (or sometimes emergent) leaves 20-40 cm",
        "bright yellow cup-shaped flowers held above water on stout stalks",
        "leaves notched at base with rounded lobes",
        "thick rhizome anchored in bottom mud"],
       0.3, 1.2, ["nationwide"],
       "Spatterdock or cow lily; more tolerant of current than white water lilies."),
    sp("Horsetail", "horsetail", "Equisetum hyemale", "plant",
       ["freshwater", "wet banks", "marshes"],
       ["emergent colonial plant, colonies about 0.15:1 extremely vertical portrait",
        "hollow segmented bamboo-like unbranched green stems",
        "each stem joint marked by a dark band of tiny tooth-like leaves",
        "cone-like spore-bearing structure at tip of fertile stems",
        "rough silica-impregnated stems (scouring rush)"],
       0.3, 0.2, ["nationwide"],
       "Living fossil; unbranched evergreen stems on wet banks."),
    sp("Cardinal Flower", "cardinal_flower", "Lobelia cardinalis", "plant",
       ["freshwater", "wet banks", "streamsides"],
       ["tall slender streamside herb, colonies about 0.3:1 vertical portrait",
        "unbranched leafy stem 60-150 cm tall",
        "spike of brilliant scarlet-red tubular flowers at top",
        "lance-shaped toothed alternate leaves along the stem",
        "hummingbird-pollinated; flowers late summer"],
       0.4, 0.35, ["nationwide"],
       "Among the most vivid native wildflowers; streamside and wet meadows."),
]


new_profiles = {
    # diving ducks
    "lesser_scaup": DIVING_DUCK,
    "greater_scaup": DIVING_DUCK,
    "long_tailed_duck": COASTAL_SEADUCK,
    "harlequin_duck": prof(
        {"lake": 4, "pond": 2, "river": 8, "stream": 9, "reservoir": 2, "marsh": 2},
        {"shallow": 7, "moderate": 8, "deep": 5},
        {"still": 2, "slow": 5, "moderate": 9, "fast": 9},
        {"heavy": 2, "moderate": 3, "sparse": 6, "none": 8},
        {"clear": 10, "moderate": 6, "murky": 2},
    ),
    "surf_scoter": COASTAL_SEADUCK,
    "white_winged_scoter": COASTAL_SEADUCK,
    "black_scoter": COASTAL_SEADUCK,
    "common_eider": COASTAL_SEADUCK,
    "red_breasted_merganser": prof(
        {"lake": 7, "pond": 3, "river": 6, "stream": 2, "reservoir": 6, "marsh": 3},
        {"shallow": 4, "moderate": 9, "deep": 8},
        {"still": 7, "slow": 7, "moderate": 5, "fast": 2},
        {"heavy": 2, "moderate": 4, "sparse": 7, "none": 8},
        {"clear": 9, "moderate": 7, "murky": 4},
    ),
    # grebes
    "horned_grebe": GREBE,
    "eared_grebe": GREBE,
    "western_grebe": prof(
        {"lake": 10, "pond": 4, "river": 4, "stream": 1, "reservoir": 9, "marsh": 6},
        {"shallow": 4, "moderate": 9, "deep": 8},
        {"still": 9, "slow": 6, "moderate": 2, "fast": 1},
        {"heavy": 4, "moderate": 6, "sparse": 7, "none": 6},
        {"clear": 9, "moderate": 7, "murky": 4},
    ),
    "clarks_grebe": prof(
        {"lake": 10, "pond": 4, "river": 4, "stream": 1, "reservoir": 9, "marsh": 6},
        {"shallow": 4, "moderate": 9, "deep": 8},
        {"still": 9, "slow": 6, "moderate": 2, "fast": 1},
        {"heavy": 4, "moderate": 6, "sparse": 7, "none": 6},
        {"clear": 9, "moderate": 7, "murky": 4},
    ),
    "red_necked_grebe": GREBE,
    # rails / coot / gallinules
    "american_coot": prof(
        {"lake": 10, "pond": 9, "river": 5, "stream": 2, "reservoir": 9, "marsh": 10},
        {"shallow": 9, "moderate": 7, "deep": 3},
        {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
        {"heavy": 9, "moderate": 9, "sparse": 6, "none": 3},
        {"clear": 6, "moderate": 8, "murky": 7},
    ),
    "common_gallinule": MARSH_BIRD,
    "sora": MARSH_BIRD,
    "virginia_rail": MARSH_BIRD,
    "king_rail": MARSH_BIRD,
    "purple_gallinule": MARSH_BIRD,
    # cranes / wading
    "sandhill_crane": prof(
        {"lake": 5, "pond": 6, "river": 6, "stream": 4, "reservoir": 5, "marsh": 10},
        {"shallow": 10, "moderate": 3, "deep": 1},
        {"still": 8, "slow": 8, "moderate": 4, "fast": 1},
        {"heavy": 5, "moderate": 8, "sparse": 9, "none": 7},
        {"clear": 7, "moderate": 8, "murky": 6},
    ),
    "whooping_crane": WADING_BIRD,
    "wood_stork": WADING_BIRD,
    "limpkin": prof(
        {"lake": 5, "pond": 8, "river": 7, "stream": 5, "reservoir": 4, "marsh": 10},
        {"shallow": 10, "moderate": 5, "deep": 1},
        {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
        {"heavy": 9, "moderate": 8, "sparse": 5, "none": 2},
        {"clear": 6, "moderate": 8, "murky": 7},
    ),
    "roseate_spoonbill": WADING_BIRD,
    "anhinga": prof(
        {"lake": 8, "pond": 7, "river": 7, "stream": 4, "reservoir": 6, "marsh": 9},
        {"shallow": 5, "moderate": 9, "deep": 6},
        {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
        {"heavy": 9, "moderate": 8, "sparse": 5, "none": 3},
        {"clear": 6, "moderate": 8, "murky": 7},
    ),
    "brown_pelican": prof(
        {"lake": 2, "pond": 1, "river": 3, "stream": 1, "reservoir": 2, "marsh": 5},
        {"shallow": 5, "moderate": 8, "deep": 9},
        {"still": 5, "slow": 7, "moderate": 8, "fast": 5},
        {"heavy": 1, "moderate": 3, "sparse": 6, "none": 9},
        {"clear": 8, "moderate": 7, "murky": 5},
    ),
    "reddish_egret": prof(
        {"lake": 3, "pond": 4, "river": 4, "stream": 3, "reservoir": 3, "marsh": 10},
        {"shallow": 10, "moderate": 3, "deep": 1},
        {"still": 7, "slow": 8, "moderate": 6, "fast": 2},
        {"heavy": 4, "moderate": 7, "sparse": 8, "none": 7},
        {"clear": 7, "moderate": 8, "murky": 6},
    ),
    # swans
    "trumpeter_swan": SWAN,
    "tundra_swan": SWAN,
    "mute_swan": SWAN,
    # shorebirds
    "killdeer": SHOREBIRD,
    "spotted_sandpiper": SHOREBIRD,
    "wilsons_snipe": MARSH_BIRD,
    "american_woodcock": prof(
        {"lake": 2, "pond": 3, "river": 4, "stream": 5, "reservoir": 1, "marsh": 7},
        {"shallow": 9, "moderate": 3, "deep": 1},
        {"still": 7, "slow": 7, "moderate": 4, "fast": 2},
        {"heavy": 10, "moderate": 8, "sparse": 4, "none": 2},
        {"clear": 5, "moderate": 7, "murky": 7},
    ),
    "greater_yellowlegs": SHOREBIRD,
    # terns/gulls
    "ring_billed_gull": TERN_GULL,
    "common_tern": TERN_GULL,
    "forsters_tern": TERN_GULL,
    "black_tern": prof(
        {"lake": 8, "pond": 6, "river": 5, "stream": 2, "reservoir": 6, "marsh": 10},
        {"shallow": 8, "moderate": 7, "deep": 3},
        {"still": 9, "slow": 7, "moderate": 3, "fast": 1},
        {"heavy": 9, "moderate": 8, "sparse": 4, "none": 2},
        {"clear": 6, "moderate": 8, "murky": 6},
    ),
    "caspian_tern": TERN_GULL,
    # marsh songbirds
    "red_winged_blackbird": MARSH_SONGBIRD,
    "yellow_headed_blackbird": MARSH_SONGBIRD,
    "marsh_wren": MARSH_SONGBIRD,
    "prothonotary_warbler": prof(
        {"lake": 4, "pond": 5, "river": 5, "stream": 5, "reservoir": 4, "marsh": 9},
        {"shallow": 9, "moderate": 5, "deep": 2},
        {"still": 8, "slow": 8, "moderate": 3, "fast": 1},
        {"heavy": 10, "moderate": 8, "sparse": 3, "none": 1},
        {"clear": 6, "moderate": 8, "murky": 7},
    ),
    "tree_swallow": prof(
        {"lake": 8, "pond": 8, "river": 7, "stream": 5, "reservoir": 7, "marsh": 9},
        {"shallow": 7, "moderate": 6, "deep": 5},
        {"still": 8, "slow": 8, "moderate": 5, "fast": 2},
        {"heavy": 6, "moderate": 8, "sparse": 7, "none": 5},
        {"clear": 7, "moderate": 8, "murky": 6},
    ),
    # water snakes
    "northern_water_snake": WATER_SNAKE,
    "brown_water_snake": WATER_SNAKE,
    "banded_water_snake": WATER_SNAKE,
    "diamondback_water_snake": WATER_SNAKE,
    "plain_bellied_water_snake": WATER_SNAKE,
    "cottonmouth": COTTONMOUTH_PROF,
    "queen_snake": QUEEN_SNAKE_PROF,
    # fish
    "american_eel": EEL_PROF,
    "chum_salmon": SALMON_PROF,
    "redfin_pickerel": PICKEREL_PROF,
    "grass_pickerel": PICKEREL_PROF,
    "bigmouth_buffalo": BUFFALO_PROF,
    "johnny_darter": FISH_STREAM_SMALL,
    "rainbow_darter": FISH_STREAM_SMALL,
    "common_shiner": FISH_STREAM_SMALL,
    "golden_shiner": prof(
        {"lake": 8, "pond": 10, "river": 5, "stream": 5, "reservoir": 7, "marsh": 7},
        {"shallow": 9, "moderate": 6, "deep": 2},
        {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
        {"heavy": 9, "moderate": 8, "sparse": 4, "none": 2},
        {"clear": 5, "moderate": 8, "murky": 7},
    ),
    "fathead_minnow": prof(
        {"lake": 6, "pond": 10, "river": 5, "stream": 7, "reservoir": 6, "marsh": 8},
        {"shallow": 10, "moderate": 5, "deep": 1},
        {"still": 9, "slow": 8, "moderate": 3, "fast": 1},
        {"heavy": 8, "moderate": 8, "sparse": 5, "none": 3},
        {"clear": 4, "moderate": 7, "murky": 9},
    ),
    "banded_killifish": KILLIFISH_PROF,
    "mummichog": prof(
        {"lake": 3, "pond": 5, "river": 4, "stream": 4, "reservoir": 2, "marsh": 10},
        {"shallow": 10, "moderate": 4, "deep": 1},
        {"still": 8, "slow": 8, "moderate": 4, "fast": 1},
        {"heavy": 8, "moderate": 8, "sparse": 5, "none": 3},
        {"clear": 4, "moderate": 7, "murky": 9},
    ),
    # amphibians
    "pickerel_frog": AMPHIBIAN_FROG,
    "mink_frog": prof(
        {"lake": 9, "pond": 9, "river": 4, "stream": 4, "reservoir": 5, "marsh": 9},
        {"shallow": 9, "moderate": 6, "deep": 2},
        {"still": 9, "slow": 7, "moderate": 2, "fast": 1},
        {"heavy": 9, "moderate": 8, "sparse": 4, "none": 2},
        {"clear": 7, "moderate": 8, "murky": 5},
    ),
    "barking_treefrog": AMPHIBIAN_FROG,
    "greater_siren": SIREN_PROF,
    "two_toed_amphiuma": SIREN_PROF,
    # plants
    "watershield": PLANT_SHALLOW,
    "water_willow": prof(
        {"lake": 4, "pond": 5, "river": 9, "stream": 10, "reservoir": 4, "marsh": 7},
        {"shallow": 10, "moderate": 4, "deep": 1},
        {"still": 4, "slow": 8, "moderate": 9, "fast": 5},
        {"heavy": 9, "moderate": 8, "sparse": 4, "none": 2},
        {"clear": 8, "moderate": 8, "murky": 4},
    ),
    "yellow_water_lily": PLANT_SHALLOW,
    "horsetail": PLANT_EMERGENT,
    "cardinal_flower": PLANT_EMERGENT,
}


def main() -> None:
    existing_species = json.load(open(SPECIES_PATH))
    existing_slugs = {sp["slug"] for sp in existing_species}
    existing_profiles = json.load(open(PROFILES_PATH))

    added = 0
    for s in new_species:
        if s["slug"] not in existing_slugs:
            existing_species.append(s)
            existing_slugs.add(s["slug"])
            added += 1
    for slug, profile in new_profiles.items():
        if slug not in existing_profiles:
            existing_profiles[slug] = profile

    with open(SPECIES_PATH, "w") as f:
        json.dump(existing_species, f, indent=2)
    with open(PROFILES_PATH, "w") as f:
        json.dump(existing_profiles, f, indent=2)

    print(f"Added {added} new species. Total: {len(existing_species)}")

    # Verify every species has a matching profile
    missing = [s["slug"] for s in existing_species if s["slug"] not in existing_profiles]
    if missing:
        print(f"WARNING: {len(missing)} species missing profiles: {missing[:5]}")
    else:
        print("OK: every species has a matching habitat profile.")

    # Category breakdown
    cats: dict[str, int] = {}
    for s in existing_species:
        cats[s["category"]] = cats.get(s["category"], 0) + 1
    print("Category breakdown:")
    for c, n in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {c}: {n}")


if __name__ == "__main__":
    main()
